### ISSUE TITLE
Organize ROS wrapper code

### ISSUE THREAD

**Issue by brnmfs** [natalnet-lpr/rgbd_rtk#43]
Organize ROS wrapper code according to functionality:

-Geometry (relative transformations between poses, point transformation, etc.) code should be in module common/geometry
-ARUCO specific code should be in module SLAM (marker detection)
-All ROS variables should be in a ROSWrapper class as instance attributes

**Comment by RodrigoSarmento** [comment]
ROSWrapper class will not be implement anymore since it won't be used by any other program
