### ISSUE TITLE
Segmentation Fault in Marker Finder

### ISSUE THREAD

**Issue by RodrigoSarmento** [natalnet-lpr/rgbd_rtk#64]

**Comment by brnmfs** [comment]
Please provide steps do reproduce the bug (in which programs this happens, which situation/parameters, etc.).

**Comment by RodrigoSarmento** [comment]
I already found the problem.

When the marker was not close from the minimum distance asked the program was still considering the marker as "found", so in the list, there was a marker found but with trash in the pose.
