### ISSUE TITLE
motion_estimator_test.cpp segmentation fault error

### ISSUE THREAD

**Issue by RodrigoSarmento** [natalnet-lpr/rgbd_rtk#84]
Segmentation Fault ocorre nesse bloco de código (linhas 95-100)
        if (i > 0)
        {
            trans = motion_estimator.estimate(tracker.prev_pts_, prev_cloud, tracker.curr_pts_, curr_cloud);
            pose = pose * trans;
        }

Dataset: ar_mm_lab1
config_files: marker_detection.yaml

**Comment by y9luiz** [comment]
acredito que seja um problema local, na minha máquina não houve esse problema, verifique o erro com o address sanitizer:

```
cmake .. -DCMAKE_CXX_FLAGS="-fsanitize=address  -fsanitize=leak -g" -DCMAKE_C_FLAGS="-fsanitize=address  -fsanitize=leak -g" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address  -fsanitize=leak" -DCMAKE_MODULE_LINKER_FLAGS="-fsanitize=address  -fsanitize=leak"
```

e poste aqui a causa para investigarmos

**Comment by RodrigoSarmento** [comment]
#92
